#!/bin/sh

eval valgrind --tool=callgrind \
     "$@ -q" 2>&1 1>/dev/null |
     sed 's/^==[0-9]*==/callgrind:/'
callgrind_annotate callgrind.out.* > "`dirname ${0}`/callgrind.log"
rm -f callgrind.out.*
