#!/bin/sh

eval valgrind --tool=memcheck \
              --num-callers=20 \
              --leak-check=yes \
              --leak-resolution=high \
              --show-reachable=yes \
     "$@ -q" 2>&1 1>/dev/null |
     sed 's/^==[0-9]*==/valgrind:/'
