.TH HTTPRY 1 "October 2006"
.SH NAME
httpry \- HTTP logging and information display tool
.SH SYNOPSIS
.B "httpry [-dp] [-b file] [-c count] [-f file] [-i interface] [-l filter] [-n count] [-oT|oX file] [-r dir] [-s string] [-u user]"
.br
.B "httpry -h or --help"
.br
.B "httpry -v or --version"
.br
.SH DESCRIPTION
.PP
.I httpry
is a tool designed for displaying and logging HTTP traffic. It is not designed
to perform analysis itself, but instead to capture, parse and log the traffic
for later analysis. It can be run in real-time displaying the traffic as it is
parsed, or as a daemon process that logs to an output file. It is written to be
as lightweight and flexible as possible, so that it can be adaptable to many
different applications.
.SH OPTIONS
.IP "-b \fIfile\fP"
Dumps a binary packet capture output file to the specified location. Note that
these are packets that pass both the pcap filter and are successfully parsed as
HTTP packets.
.IP "-c \fIfile\fP"
Provides a configuration file to read settings from at initilization. These
settings can be overridden by command line arguments. See the included example
configuration file for the available options and proper syntax.
.IP "-d"
Runs the program as a daemon process. All program status output will be
sent to the syslog. A pid file is created for the process in /var/run/httpry.pid
by default. Requires -oT or -oX.
.IP "-f \fIfile\fP"
Provide an input capture file to read from instead of performing a
live capture. The program expects a valid capture file as input. Note that this
does not require the program to be run as root, as no access to the NIC is
required.
.IP "-h | --help"
Displays a brief description of these options, after which the program
terminates.
.IP "-i \fIinterface\fP"
Specifies an ethernet interface for the program to listen on.
This is optional; by default the program will poll the system for a list of
interfaces and select the first one that it finds.
.IP "-l \fIfilter\fP"
Allows the default capture filter to be overridden by a filter
that follows the tcpdump format. Useful for capturing traffic on non-standard
ports or to/from specific hosts.
.IP "-n \fIcount\fP"
Specifies a number of HTTP packets to parse, following which the
program will terminate.
.IP "-oT, -oX \fIfile\fP"
Provides an output file for writing parsed packet data. The switch oT will
print the output in a tab-delimited text format and the switch oX will print
the output in XML format. These two switches cannot be combined. You can use
'-' for the filename to force printing to STDOUT, however errors and other
informational messages will still print to STDERR. Note that if the program
is running as a daemon, its base directory may change so an absolute path to
the output file should be specified.
.IP "-p"
Disables promiscuous mode on the NIC. Under most circumstances this should
not be required.
.IP "-r \fIdir\fP"
Allows a running directory to be specified when running in daemon mode. By
default this is set to '/', which should be adequate for most uses.
.IP "-s \fIstring\fP"
Specifies a comma-delimited string that defines the HTTP fields to output. See
the included documentation for the allowed options to use in this string.
.IP "-u \fIuser\fP"
Allows an alternate user to take ownership of the process. This is
particularly useful when running in daemon mode. Note that you still need root
privileges in order to run the program; it will switch to the alternate
credentials once initialization is complete.
.IP "-v | --version"
Displays the program name and version number, after which the program
terminates.
.SH BUGS
There are no known issues that I am aware of.
.SH AUTHOR
.I httpry
was written by Jason Bittel <jbittel@corban.edu>. All rights reserved.
See included LICENSE file for specific licensing information
