Document: httpry
Title: Debian httpry Manual
Author: <insert document author here>
Abstract: This manual describes what httpry is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/httpry/httpry.sgml.gz

Format: postscript
Files: /usr/share/doc/httpry/httpry.ps.gz

Format: text
Files: /usr/share/doc/httpry/httpry.text.gz

Format: HTML
Index: /usr/share/doc/httpry/html/index.html
Files: /usr/share/doc/httpry/html/*.html
